mutation_test_game/mutation_test/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('index', views.index, name='index'),
    # path('login', views.login, name='login'),
    # path('register', views.register, name='register'),
    path('diff_1', views.diff_1, name='diff_1'),
    path('diff_1/<str:bangou>/', views.diff_1, name='diff_1_get'),
    path('diff_2', views.diff_2, name='diff_2'),
    path('diff_2/<str:bangou>/', views.diff_2, name='diff_2_get'),
    path('diff_3', views.diff_3, name='diff_3'),
    path('diff_3/<str:bangou>/', views.diff_3, name='diff_3_get'),
    path('ajax', views.ajax, name='ajax'),
    path('tool', views.tool_download, name='tool_download'),
    path('diff_1_load', views.diff_1_load, name='diff_1_load'),
    path('diff_2_load', views.diff_2_load, name='diff_2_load'),
    path('diff_3_load', views.diff_3_load, name='diff_3_load'),
]

mutation_test_game/mutation_test_game/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('mutation_test.urls'))
]

mutation_test_game/mutation_test/models.py
from django.db import models

# Create your models here.

mutation_test_game/mutation_test/forms.py
from django import forms

class UploadFileForm(forms.Form):
    file1 = forms.FileField()

mutation_test_game/mutation_test/views.py
import sys, datetime, time, random
import traceback
sys.path.append("/home/user777/Python_Mutationtest_Project/mutation_tool")
import mutation
sys.path.append("/home/user777/Python_Mutationtest_Project/mutation_test_game/shukudai/T35")
import T35, mutateT35
sys.path.append("/home/user777/Python_Mutationtest_Project/mutation_test_game/shukudai/diff_1/")
import AssertCode_Processer1
sys.path.append("/home/user777/Python_Mutationtest_Project/mutation_test_game/shukudai/diff_2/")
import AssertCode_Processer2
sys.path.append("/home/user777/Python_Mutationtest_Project/mutation_test_game/shukudai/diff_3/")
import AssertCode_Processer3
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from django.template.response import TemplateResponse
from django.contrib import messages
from .forms import UploadFileForm
# filehandler = __import__("/mutation_test/file_handler")
import mutation_test.file_handler as fh

# 確認變數是否已經定義
def isset(v):
    try :
        type (eval(v)) 
    except : 
        return  0  
    else :
        return  1

def index(request):
    # print(fh.handle_uploaded_file())
    # return TemplateResponse(request, template_name, args)
    return render(request,'mutation_test/index.html')

    # return HttpResponse(ans)
    # Create your views here.

# 輸入10, 9 , 8
#Level-1題目處理
def diff_1(request, bangou=0):

    # 建立不重複的數字list與紀錄對應時間的字典檔
    try:
        print(diff_1.Num_list)
    except AttributeError:
        diff_1.Num_list = []
        diff_1.Num_dic = dict()

        for i in range(1,1001):
            diff_1.Num_list.append(str(i))
        # print(diff_1.Num_list)

    if request.method == 'POST':
        # print(request.POST['input'])
        #分割字串
        # print(request.POST)
        a = request.POST['input'].split(',')
        # print(a)
        num_ar = []
        #捨棄非數字的輸入
        for i in a:
            try:
                
                num_ar.append(int(i))
            except:
                print("有非數字的輸入")
                continue
        print(num_ar)
        if num_ar == []:
            return JsonResponse({"no_input": "請輸入測試資料"})
        output_string, killper, kill_status_record = AssertCode_Processer1.AssertCode(num_ar)
        # output_string, killper, kill_status_record = AssertCode_Processer1.AssertCode([("12234"), ("214124")])
        # print(output_string)
        # print(output_string, killper)
        
        return JsonResponse({'output_string':output_string, 'killper': killper, "kill_status_record": kill_status_record})

    elif request.method == 'GET':
        #bangou=0代表是第一次進入網頁
        if(bangou == 0):
            # Num 是指派給使用者的數字
            Num = diff_1.Num_list[0]
            # 將此數字記錄到字典裡
            diff_1.Num_dic[diff_1.Num_list[0]] = ''
            # print(diff_1.Num_dic)
            del diff_1.Num_list[0]
            return redirect('/diff_1/'+Num)
        else:
        # 抓時間出來
            print(bangou)
            print('diff_dic = ',diff_1.Num_dic)
            
            try:
                if diff_1.Num_dic[bangou] == '':
                    diff_1.Num_dic[bangou] = datetime.datetime.now()
                    now = datetime.datetime.now()
                    print(diff_1.Num_dic[bangou])
                    time_subtract = time.mktime(now.timetuple()) - time.mktime(diff_1.Num_dic[bangou].timetuple())
                    timeArray = time.localtime(time_subtract)
                    timecout = time.strftime("%M:%S", timeArray)

                else:
                    now = datetime.datetime.now()
                    time_subtract = time.mktime(now.timetuple()) - time.mktime(diff_1.Num_dic[bangou].timetuple())
                    timeArray = time.localtime(time_subtract)
                    timecout = time.strftime("%M:%S", timeArray)

                return render(request, 'mutation_test/diff_1.html',{"timecout":timecout, "bangou":bangou})
            except Exception as e:
                error_class = e.__class__.__name__ #取得錯誤類型
                detail = e.args[0] #取得詳細內容
                cl, exc, tb = sys.exc_info() #取得Call Stack
                lastCallStack = traceback.extract_tb(tb)[-1] #取得Call Stack的最後一筆資料
                fileName = lastCallStack[0] #取得發生的檔案名稱
                lineNum = lastCallStack[1] #取得發生的行號
                funcName = lastCallStack[2] #取得發生的函數名稱
                errMsg = "File \"{}\", line {}, in {}: [{}] {}".format(fileName, lineNum, funcName, error_class, detail)
                print(errMsg)
                # pass
            
            return render(request, 'mutation_test/diff_1.html',{"error":"請回到首頁"})


def diff_1_load(request):
    basedir = "/home/user777/Python_Mutationtest_Project/mutation_test_game/"
    all_shukudai = []
    
    for i in range(1,4):
        with open(basedir + "test_{num}.py".format(num=i), "r", encoding="UTF-8") as file:
            all_shukudai.append(file.read())
    # for i in all_shukudai:NNNN
        # print(i)
    print(1)

    return JsonResponse({'all_shukudai' : all_shukudai})

#Level-2題目處理
def diff_2(request,bangou=0):
        # 建立不重複的數字list與紀錄對應時間的字典檔
    try:
        print(diff_2.Num_list)
    except AttributeError:
        diff_2.Num_list = []
        diff_2.Num_dic = dict()

        for i in range(1,1001):
            diff_2.Num_list.append(str(i))
        # print(diff_1.Num_list)

    if request.method == 'POST':
        # print(request.POST['input'])
        #分割字串
        # print(request.POST)
        a = request.POST['input'].split(',')
        # print(a)
        num_ar = []
        #捨棄非數字的輸入
        for i in a:
            try:
                num_ar.append(int(i))
            except:
                print("有非數字的輸入")
                continue
        print(num_ar)
        if num_ar == []:
            return JsonResponse({"no_input": "請輸入測試資料"})
        output_string, killper, kill_status_record = AssertCode_Processer2.AssertCode(num_ar)
        # output_string, killper, kill_status_record = AssertCode_Processer1.AssertCode([("12234"), ("214124")])
        # print(output_string)
        # print(output_string, killper)
        
        return JsonResponse({'output_string':output_string, 'killper': killper, "kill_status_record": kill_status_record})

    elif request.method == 'GET':
        #bangou=0代表是第一次進入網頁
        if(bangou == 0):
            # Num 是指派給使用者的數字
            Num = diff_2.Num_list[0]
            # 將此數字記錄到字典裡
            diff_2.Num_dic[diff_2.Num_list[0]] = ''
            # print(diff_1.Num_dic)
            del diff_2.Num_list[0]
            return redirect('/diff_2/'+Num)
        else:
        # 抓時間出來
            # print(bangou)
            # print('diff_dic = ',diff_2.Num_dic)
            
            try:
                if diff_2.Num_dic[bangou] == '':
                    diff_2.Num_dic[bangou] = datetime.datetime.now()
                    now = datetime.datetime.now()
                    # print(diff_2.Num_dic[bangou])
                    time_subtract = time.mktime(now.timetuple()) - time.mktime(diff_2.Num_dic[bangou].timetuple())
                    timeArray = time.localtime(time_subtract)
                    timecout = time.strftime("%M:%S", timeArray)
                else:
                    now = datetime.datetime.now()
                    time_subtract = time.mktime(now.timetuple()) - time.mktime(diff_2.Num_dic[bangou].timetuple())
                    timeArray = time.localtime(time_subtract)
                    timecout = time.strftime("%M:%S", timeArray)

                return render(request, 'mutation_test/diff_2.html',{"timecout":timecout, "bangou":bangou})
            except Exception as e:
                error_class = e.__class__.__name__ #取得錯誤類型
                detail = e.args[0] #取得詳細內容
                cl, exc, tb = sys.exc_info() #取得Call Stack
                lastCallStack = traceback.extract_tb(tb)[-1] #取得Call Stack的最後一筆資料
                fileName = lastCallStack[0] #取得發生的檔案名稱
                lineNum = lastCallStack[1] #取得發生的行號
                funcName = lastCallStack[2] #取得發生的函數名稱
                errMsg = "File \"{}\", line {}, in {}: [{}] {}".format(fileName, lineNum, funcName, error_class, detail)
                print(errMsg)
                # pass
            
            return render(request, 'mutation_test/diff_2.html',{"error":"請回到首頁"})

def diff_2_load(request):
    basedir = "/home/user777/Python_Mutationtest_Project/mutation_test_game/"
    all_shukudai = []
    
    for i in range(1,7):
        with open(basedir + "test_{num}.py".format(num=i), "r", encoding="UTF-8") as file:
            all_shukudai.append(file.read())
    # for i in all_shukudai:NNNN
        # print(i)
    print(all_shukudai)

    return JsonResponse({'all_shukudai' : all_shukudai})
#Level-3題目處理
def diff_3(request, bangou=0):
    # 建立不重複的數字list與紀錄對應時間的字典檔
    try:
        print(diff_3.Num_list)
    except AttributeError:
        diff_3.Num_list = []
        diff_3.Num_dic = dict()

        for i in range(1,1001):
            diff_3.Num_list.append(str(i))
        # print(diff_1.Num_list)

    if request.method == 'POST':
        # print(request.POST['input'])
        #分割字串
        # print(request.POST)
        a = request.POST['input'].split(',')
        # print(a)
        num_ar = []
        #捨棄非數字的輸入
        for i in a:
            try:
                num_ar.append(int(i))
            except:
                print("有非數字的輸入")
                continue
        print(num_ar)
        if num_ar == []:
            return JsonResponse({"no_input": "請輸入測試資料"})
        output_string, killper, kill_status_record = AssertCode_Processer3.AssertCode(num_ar)
        # output_string, killper, kill_status_record = AssertCode_Processer1.AssertCode([("12234"), ("214124")])

mutation_test_game/mutation_test/templates/mutation_test/backup.html
{% extends "../inherit/sample.html" %}

{% block head %}
<style>
    .relative1 {
    position: relative;
    }
    .relative2 {
    position: relative;
    top: -30px;
    left: 10px;
    width: 500px;
    background-color: rgba(255,255,255,0);
    }

    .overflow_scroll{   
        overflow:scroll;
    }

    .wh30060{
        width:400px;
        height:300px;
    }
    
</style>

<style>
    .graph {
    position: relative; /* IE is dumb */
    width: 500px;
    border: 1px solid #B1D632;
    padding: 2px;
    }
    .graph .bar {
    display: block;
    position: static;
    background: #B1D632;
    text-align: center;
    color: #333;
    height: 2em;
    line-height: 2em;
    }
</style>

{% endblock %}

{% block temp %}
<div class="container">
    <h1 class="" style="margin-top:20px;">Level-3</h1>
    <div class="row">
        <div class="col-6 border overflow_scroll wh30060">
<pre>
{{ suc }}
# 這是題目
def T35():
    if 3 >= 5:
        return "yes"
    else:
        return "no"
def T69():
    if 6+1 < 9:
        return "yes"
    else:
        return "no"
</pre>
        </div>
        <div class="col-3 align-self-end">
            <!--
            <form action="upload_file" method="POST" enctype="multipart/form-data">
                <br>
                <input type="file" name="file1" required="" id="id_file1">
                <input type="hidden" name="page" value="diff_1">
                <input type="submit" value="送出表單">
                <br>
            </form>
            -->
            
            {% csrf_token %}
            <input type="file" class='pb1 rounded' name="file1" required="" id="Upfile">
            <input type="hidden" name="page" value="diff_1">
            <button type='button' class = 'border-light rounded' onclick = "loadXMLDoc()">Test</button>
        </div>
        <div class="col-3">
        </div>
    </div>
    <div class="row">
        <div class="col-6">
            <hr>
        </div>
    </div>
    <h1 class="" style="">輸出結果</h1>
    <div class="row pt1">
        <div class="col-6 border overflow_scroll wh30060 ">
<pre id='output'>
{{ans}}
{{ error }}
</pre>
        </div>
        <div class='col-6'>
            <div class="graph">
            <strong id="myBar" class="bar relative1" style="width:0%;"></strong>
            </div>
            <p class='text-center relative2'>kill rate</p>
            <p id='myP' class='text-center relative2' ></p>
            <p id='myp2' class='text-center relative2' ></p>
        </div>
    </div>
</div>

<script>
    function loadXMLDoc()
    {
        var xmlhttp;
        if (typeof(document.getElementById("Upfile").files[0]) == 'undefined')
            {
                alert("請選擇要上傳的檔案")
                return;
            }
        if (window.XMLHttpRequest)
        {// code for IE7+, Firefox, Chrome, Opera, Safari
        xmlhttp=new XMLHttpRequest();
        }
        else
        {// code for IE6, IE5
        xmlhttp=new ActiveXObject("Microsoft.XMLHTTP");
        }
        xmlhttp.onreadystatechange=function()
        {
        if (xmlhttp.readyState==4 && xmlhttp.status==200)
            {
                var elem1 = document.getElementById("myBar");
                var elem2 = document.getElementById("myP");
                var width = 1;
                
                js_ans = JSON.parse(xmlhttp.response)

                var id = setInterval(frame, 20);
                var elemp2 = document.getElementById('myp2')
                elemp2.innerHTML = "恭喜你的變異程式擊殺率有" + js_ans.killper + "% 查看左側輸出欄可以得知那些程式未被順利kill"
                document.getElementById("output").innerHTML = js_ans.ans
                function frame() {
                    if (width >= parseFloat(js_ans.killper)) {
                        elem1.style.width = parseFloat(js_ans.killper) + '%';
                        elem2.innerHTML = parseFloat(js_ans.killper) + '%';
                        clearInterval(id);
                    } else {
                        width++;
                        elem1.style.width = width + '%';
                        elem2.innerHTML = width + '%';
                    }
                }
            }
        }

        xmlhttp.open("POST","{% url 'upload_file' %}",true);
        xmlhttp.setRequestHeader('Conten-Type', 'application/x-www-foorm-urlencoded;charset-UTF-8');  //POST資料請求頭
        var f_obj = document.getElementById("Upfile").files[0];
        var data = new FormData();

        data.append("csrfmiddlewaretoken",$("[name='csrfmiddlewaretoken']").val());
        data.append("file1", f_obj);
        data.append("page", "diff_1");
        xmlhttp.send(data);
    }
</script>
{% endblock %}

<!-- <pre id='unmutate' style="">
# 變異前
def T35(NumX):
    if 3 > NumX:
        return "yes"
    else:
        return "no"
</pre>

<pre id='mutated' style="display:none">
# 變異後
def T35(NumX):
    if 3 < NumX:
        return "yes"
    else:
        return "no"
</pre>

<pre id='assert_part' style="display:none">
# assert_func
import T35
def assert_func(ans,NumX):
    if T35(NumX) == ans:
        return "通過"
    else:
        return "失敗"
ans = "no"
print(assert_func(ans, NumX))
</pre> -->

mutation_test_game/mutation_test/templates/mutation_test/index.html
{% extends "../inherit/sample.html" %}

{% block temp %}
    <div class="container">
        <div class="row text-center" style = "padding-top:30px;padding-bottom:20px">
            <div class="col" style="font-family:Microsoft JhengHei; font-size:30px">
                <strong>變異測試小遊戲</strong>
            </div>
        </div>

        <div class="row">
        <div class="col-sm-6">
            <div class="card">
            <div class="card-body">
                <h5 class="card-title">Level-1</h5>
                <p class="card-text">三個變異程式</p>
                <a href="diff_1" class="btn btn-primary">進入</a>
            </div>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="card">
            <div class="card-body">
                <h5 class="card-title">Level-2</h5>
                <p class="card-text">六個變異程式</p>
                <a href="diff_2" class="btn btn-primary">進入</a>
            </div>
            </div>
        </div>
        </div>
        <div class="row justify-content-center" style="padding-top: 10px;">
        <div class="col-sm-6">
            <div class="card">
            <div class="card-body">
                <h5 class="card-title">Level-3</h5>
                <p class="card-text">九個變異程式</p>
                <a href="{% url 'diff_3' %}" class="btn btn-primary">進入</a>
            </div>
            </div>
        </div>

        </div>

        {% comment %} <div class="border border-primary" style="margin-top:20px">
            <div class="btn-group btn-group-justified pb1" role="group" aria-label="Justified button group">
                <a class="btn btn-primary" href="#" role="button">Level-1</a>
                <a class="btn btn-primary" href="#" role="button">Level-2</a>
                <a class="btn btn-primary" href="#" role="button">Level-3</a>
                <a class="btn btn-primary" href="#" role="button">Level-4</a>
            </div >
            <div class="row justify-content-center" style="padding-top:10px">
                <div class="col-2"><span style="">1.Mapldddde</span></div>
            </div>
            <div class="row justify-content-center align-items-center" style="padding-top:10px" >
                <div class="col-2"><span>2. Story</span></div>
            </div>
            <div class="row justify-content-center align-items-center" style="padding-top:10px">
                <div class="col-2"><span>3. Nope</span></div>
            </div>
            <div class="row justify-content-center align-items-center pb1" style="padding-top:10px">
                <div class="col-2"><span>4. ゼロ</span></div>
            </div>
        </div> {% endcomment %}
    </div>
{% endblock %}

mutation_test_game/mutation_test/templates/mutation_test/upload.html
{% extends "../inherit/sample.html" %}
{% block upload %}
    <form action="upload_file" method="POST" enctype="multipart/form-data">
        <br>
        {{ form }}
        <input class="" type="submit" value="上傳">
        <br>
        {% csrf_token %}
    </form>
{% endblock %}

mutation_test_game/mutation_test/templates/mutation_test/zzz.html
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
    Launch demo modal
  </button>
  
  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          ...
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary">Save changes</button>
        </div>
      </div>
    </div>
  </div>